function t121_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var videoBlock=document.getElementById('youtubeiframe'+recid);var videoParent=videoBlock?videoBlock.parentNode:null;var videoWidth=videoBlock?videoBlock.offsetWidth:0;var videoHeight=videoWidth*0.5625;if(videoBlock)videoBlock.style.height=videoHeight+'px';if(videoParent)videoParent.style.height=videoHeight+'px';var videoLazy=rec?rec.querySelector('.t-video-lazyload'):null;if(videoLazy){var iframeLazy=videoLazy.querySelector('iframe');var heightLazy=videoLazy.offsetWidth*0.5625;videoLazy.style.height=heightLazy+'px';if(iframeLazy)iframeLazy.style.height=heightLazy+'px';setTimeout(function(){videoBlock=document.getElementById('youtubeiframe'+recid);videoWidth=videoBlock?videoBlock.offsetWidth:0;if(videoBlock)videoBlock.style.height=(videoWidth*0.5625)+'px'},200)}}
function t142_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t142__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom)+5;var textHeight=button.scrollHeight;if(buttonHeight<textHeight){button.classList.add('t142__submit-overflowed')}}
function t190_scrollToTop(){var duration=700;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=0-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t190__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t190__animateScroll(){currentTime+=increment;window.scrollTo(0,t190__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t190__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t190__animateScroll()}
function t223_initThumbnail(rec){t_onFuncLoad('t223_setThumbnailHeight',function(){t223_setThumbnailHeight(rec)});t_onFuncLoad('t223_setThumbnail',function(){t223_setThumbnail(rec)});t_onFuncLoad('t223_setYouTubeIframeHeight',function(){t223_setYouTubeIframeHeight(rec)})}
function t223_setThumbnail(rec){var thumbnails=rec.querySelectorAll('.t223__video-thumbnail');if(!thumbnails.length)return;Array.prototype.forEach.call(thumbnails,function(thumbnail){var blockTop=thumbnail.getBoundingClientRect().top;var windowHeight=document.documentElement.clientHeight;var scrollDiffHeigth=400;if(window.pageYOffset>blockTop-windowHeight-scrollDiffHeigth){var youTubeID=thumbnail.getAttribute('data-youtube-id').trim();thumbnail.style.backgroundImage='url("https://img.youtube.com/vi/'+youTubeID+'/sddefault.jpg")';thumbnail.addEventListener('click',function(event){event.preventDefault();var youTubeWrapper=thumbnail.parentNode;var youTubeIframe='<iframe class="t223__youtube-iframe" width="100%" height="" src="https://www.youtube.com/embed/'+youTubeID+'?autoplay=1&rel=0" frameborder="0" allow="autoplay" allowfullscreen></iframe>';thumbnail.innerHTML=youTubeIframe;t223_setYouTubeIframeHeight(rec)})}})}
function t223_setThumbnailHeight(rec){var thumbnail=rec.querySelectorAll('.t223__video-thumbnail');if(!thumbnail.length)return;Array.prototype.forEach.call(thumbnail,function(image){var imageWidth=image.offsetWidth;var computedHeight=imageWidth/(16/9);image.style.height=computedHeight+'px'})}
function t223_setYouTubeIframeHeight(rec){var youTubeIframes=rec.querySelectorAll('iframe');if(!youTubeIframes.length)return;Array.prototype.forEach.call(youTubeIframes,function(youTubeIframe){var iframeParent=youTubeIframe.parentNode;var iframeParentWidth=iframeParent.offsetWidth;var computedHeight=iframeParentWidth/(16/9);youTubeIframe.height=computedHeight})}
function t270_scroll(hash,offset){if(!hash)return;if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return!0}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);var isSafari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==='[object SafariRemoteNotification]'})(!window.safari||(typeof safari!=='undefined'&&window.safari.pushNotification));var isIE=!1||!!document.documentMode;if(isSafari||isIE){t_throttle(t270_scrollToEl(target),500)}else{t_throttle(window.scrollTo({left:0,top:target,behavior:'smooth',}),500)}
if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_scrollToEl(target,duration){if(!duration){duration=400}
if(target===window.pageYOffset){return!1}
var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(Math.abs(window.pageYOffset-target)*10)/duration;var scrollInterval=setInterval(function(){if(cashedDiff>target){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>target&&window.pageYOffset<=target){document.body.removeAttribute('data-scrollable');clearInterval(scrollInterval)}else if(cashedDiff<=target&&window.pageYOffset>=target){document.body.removeAttribute('data-scrollable');window.scrollTo(0,target);clearInterval(scrollInterval)}},10);var scrollTimeout=setTimeout(function(){clearInterval(scrollInterval);document.body.removeAttribute('data-scrollable');clearTimeout(scrollTimeout)},duration*2)}
function t393_appearMenu(recId){if(window.innerWidth>980){var recs=document.querySelectorAll('.t393');var scrollTop=window.pageYOffset;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);for(var i=0;i<recs.length;i++){var rec=recs[i];var appearOffset=rec.getAttribute('data-appearoffset');var hideOffset=rec.getAttribute('data-hideoffset');if(appearOffset){if(appearOffset.indexOf('vh')>-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);if(scrollTop>=appearOffset){if(rec.style.visibility==='hidden'){rec.style.visibility='visible';t393__fadeIn(rec)}}else{rec.style.visibility='hidden'}}
if(hideOffset){if(hideOffset.indexOf('vh')>-1){hideOffset=Math.floor((window.innerHeight*(parseInt(hideOffset)/100)))}
hideOffset=parseInt(hideOffset,10);if(scrollTop+window.innerHeight>=documentHeight-hideOffset){if(rec.style.visibility!=='hidden'){rec.style.visibility='hidden'}}else if(appearOffset){if(scrollTop>=appearOffset){rec.style.visibility='visible'}}else{rec.style.visibility='visible'}}}}}
function t393__fadeIn(el){if(el.style.display==='block')return;var opacity=0;el.style.opacity=opacity;el.style.display='block';var timer=setInterval(function(){el.style.opacity=opacity;opacity+=0.1;if(opacity>=1.0){clearInterval(timer);el.style.display=''}},30)}
function t446_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var linkItems=rec.querySelectorAll('.t-menu__link-item');var subMenuLinks=rec.querySelectorAll('.t-menusub__link-item');Array.prototype.forEach.call(linkItems,function(link){link.addEventListener('click',function(){if(link.classList.contains('t-menusub__target-link')||link.classList.contains('tooltipstered')||link.classList.contains('t794__tm-link')||link.classList.contains('t966__tm-link')||link.classList.contains('t978__tm-link'))return;t446_hideMenuOnMobile(link,rec)})});Array.prototype.forEach.call(subMenuLinks,function(subMenuLink){subMenuLink.addEventListener('click',function(){t446_hideMenuOnMobile(subMenuLink,rec)})})}
function t446_setLogoPadding(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t446');var logo=menu?menu.querySelector('.t446__logowrapper'):null;var logoWidth=logo?logo.offsetWidth:0;var leftWrapper=menu?menu.querySelector('.t446__leftwrapper'):null;var rightWrapper=menu?menu.querySelector('.t446__rightwrapper'):null;if(leftWrapper)leftWrapper.style.paddingRight=((logoWidth/2)+50)+'px';if(rightWrapper)rightWrapper.style.paddingLeft=((logoWidth/2)+50)+'px'}
function t446_checkOverflow(recid,menuheight){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t446'):null;if(!menu)return;var rightWrapper=menu.querySelector('.t446__rightwrapper');var rightMenuWrap=rightWrapper?rightWrapper.querySelector('.t446__rightmenuwrapper'):null;var additionalWrap=rightWrapper?rightWrapper.querySelector('.t446__additionalwrapper'):null;var burgerWrapOverflow=rightWrapper?rightWrapper.querySelector('.t446__burgerwrapper_overflow'):null;var burgerWrap=rightWrapper?rightWrapper.querySelector('.t446__burgerwrapper_withoutoverflow'):null;var rightWrapperWidth=t446_getPureWidth(rightWrapper);var rightMenuWrapWidth=rightMenuWrap?rightMenuWrap.offsetWidth:0;var additionalWrapWidth=additionalWrap?additionalWrap.offsetWidth:0;var additionalWrapFloating=additionalWrap?additionalWrap.style.float||window.getComputedStyle(additionalWrap).float:'';var blockHeight=menuheight>0?menuheight:80;if(window.innerWidth>980&&rightMenuWrapWidth+additionalWrapWidth>rightWrapperWidth){menu.style.height=(blockHeight*2)+'px';if(additionalWrap)additionalWrap.style.float='right';if(burgerWrapOverflow)burgerWrapOverflow.style.display='table-cell';if(burgerWrap)burgerWrap.style.display='none'}else{if(menu.offsetHeight>blockHeight)menu.style.height=blockHeight+'px';if(additionalWrap&&additionalWrapFloating==='right')additionalWrap.style.float='none';if(burgerWrapOverflow)burgerWrapOverflow.style.display='none';if(burgerWrap)burgerWrap.style.display='table-cell'}}
function t446_getPureWidth(el){if(!el)return 0;var elWidth=el.offsetWidth;var elPaddingLeft=parseInt(window.getComputedStyle(el).paddingLeft,10)||0;var elPaddingRight=parseInt(window.getComputedStyle(el).paddingRight,10)||0;return elWidth-(elPaddingLeft+elPaddingRight)}
function t446_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t446__list_item a[href=\''+url+'\'], '+'.t446__list_item a[href=\''+url+'/\'], '+'.t446__list_item a[href=\''+pathname+'\'], '+'.t446__list_item a[href=\'/'+pathname+'\'], '+'.t446__list_item a[href=\''+pathname+'/\'], '+'.t446__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t446_checkAnchorLinks(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<980)return;var navLinks=rec.querySelectorAll('.t446__list_item a[href*=\'#\']');navLinks=Array.prototype.filter.call(navLinks,function(link){return!link.classList.contains('tooltipstered')});if(navLinks.length)t446_catchScroll(navLinks)}
function t446_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t446_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t446_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t446_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t446').bind('displayChanged',function(){t446_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t446_updateSectionsOffsets(sections)})})}
setInterval(function(){t446_updateSectionsOffsets(sections)},5000);t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t446_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t446_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t446_getSectionByHref(currentLink){if(!currentLink)return;var href=currentLink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&currentLink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t446_setBg(recid){var menuBlocks=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t446_appearMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t446_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t446_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t446_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t446_changebgopacitymenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t446_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t446');var burger=rec.querySelector('.t446__mobile');if(menu&&menu.classList.contains('t446__mobile_burgerhook')){var mobileBurger=burger?burger.querySelector('.t446__mobile_burger'):null;if(mobileBurger){var mobileBurgerParent=mobileBurger.parentElement;var link=document.createElement('a');link.href='#menuopen';if(mobileBurgerParent){link.appendChild(mobileBurger);mobileBurgerParent.appendChild(link)}}}else if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t446_opened')){t446_fadeOut(menu,300);burger.classList.remove('t446_opened')}else{t446_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t446_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu)menu.style.opacity='';if(menu)menu.style.display='';if(burger)burger.classList.remove('t446_opened')}},200));var linkItems=rec.querySelectorAll('.t-menu__link-item');Array.prototype.forEach.call(linkItems,function(link){link.addEventListener('click',function(){if(!link.classList.contains('t966__tm-link')&&!link.classList.contains('t978__tm-link')){t446_hideMenuOnMobile(link,rec)}})});var logoWrappers=rec.querySelectorAll('.t446__logowrapper2 a');Array.prototype.forEach.call(logoWrappers,function(logoWrapper){logoWrapper.addEventListener('click',function(){t446_hideMenuOnMobile(link,rec)})})}
function t446_hideMenuOnMobile(link,rec){if(!rec||!link||window.innerWidth>=980)return!1;var url=link.href?link.href.trim():'';var menu=rec.querySelector('.t446');var burger=rec.querySelector('.t446__mobile');if(url&&link.matches('[href*="#"]')){if(burger)burger.classList.remove('t446_opened');if(menu){if(menu.classList.contains('t446__positionabsolute')||(burger&&!burger.classList.contains('.t446__positionfixed'))){menu.style.display='none';menu.style.opacity='0'}else{t446_fadeOut(menu,300)}}}}
function t446_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t446_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed');if(container)container.style.height='auto'}else{menu.classList.remove('t450__overflowed');if(container)container.style.height=''}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__burger_container'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t461_setLogoPadding(recid){if(window.innerWidth>980){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t461'):null;var logo=menu?menu.querySelector('.t461__logowrapper'):null;var leftSide=menu?menu.querySelector('.t461__leftwrapper'):null;var rightSide=menu?menu.querySelector('.t461__rightwrapper'):null;var logoWidth=logo?logo.clientWidth:0;if(leftSide)leftSide.style.paddingRight=((logoWidth/2)+50)+'px';if(rightSide)rightSide.style.paddingLeft=((logoWidth/2)+50)+'px'}}
function t461_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t461__list_item a[href=\''+url+'\'], '+'.t461__list_item a[href=\''+url+'/\'], '+'.t461__list_item a[href=\''+pathname+'\'], '+'.t461__list_item a[href=\'/'+pathname+'\'], '+'.t461__list_item a[href=\''+pathname+'/\'], '+'.t461__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t461_checkAnchorLinks(recid){if(window.innerWidth>=960){var rec=document.getElementById('rec'+recid);var navLinks=rec?rec.querySelectorAll('.t461__desktoplist .t461__list_item a[href*=\'#\']'):[];navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){t461_catchScroll(navLinks)}}}
function t461_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t461_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t461_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t461_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t461').bind('displayChanged',function(){t461_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t461');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t461_updateSectionsOffsets(sections)})})}
setInterval(function(){t461_updateSectionsOffsets(sections)},5000);t461_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t461_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t461_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t461_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t461_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t461_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t461_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t461_setBg(recid){var menuBlocks=document.querySelectorAll('.t461');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t461_appearMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t461');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t461_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t461_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t461_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t461_changebgopacitymenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t461');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t461_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t461');var burger=rec.querySelector('.t461__mobile');if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t461_opened')){t461_fadeOut(menu,300);burger.classList.remove('t461_opened')}else{t461_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t461_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu.style.opacity)menu.style.opacity='';if(menu.style.display==='none')menu.style.display=''}else{if(menu.style.transform)menu.style.transform=''}}))}
function t461_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t461_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t480_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var isJquery=typeof jQuery!=='undefined';t480_setHeight(recId);if(window.isMobile){if(isJquery){$(window).on('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}else{window.addEventListener('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}}else{window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t480_setHeight(recId)}))}
if(isJquery){$(container).on('displayChanged',function(){t480_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t480_setHeight(recId)})}}
function t480_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var sizer=rec.querySelector('.t480__sizer');var sizerStyle=getComputedStyle(sizer,null);var sizerPaddingTop=parseInt(sizerStyle.paddingTop);var sizerPaddingBottom=parseInt(sizerStyle.paddingBottom);var sizerPaddingLeft=parseInt(sizerStyle.paddingLeft);var sizerPaddingRight=parseInt(sizerStyle.paddingRight);var sizerHeight=sizer.clientHeight-(sizerPaddingTop+sizerPaddingBottom);var sizerWidth=sizer.clientWidth-(sizerPaddingLeft+sizerPaddingRight);var ratio=sizerWidth/sizerHeight;var imgWrapper=rec.querySelector('.t480__blockimg');var imgWidth=imgWrapper.clientWidth;var sizerAttrStyle=sizer.getAttribute('style');var windowHeight=window.innerHeight;if(window.isMobile&&sizerAttrStyle&&sizerAttrStyle.indexOf('vh')!==-1){sizerHeight=document.documentElement.clientHeight*parseFloat(windowHeight/sizerHeight);imgWrapper.style.height=(imgWidth/ratio)+'px'}else if(sizerHeight!=windowHeight){imgWrapper.style.height=(imgWidth/ratio)+'px'}}
function t505__createPieChart(recId,data1,data2,data3,data4,sectorColor,pieBgColor,bgcolor,blocksNumber,diagramWidth,diameter){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t505');if(!container)return;var radius;if(diameter>300||diameter==''||diameter<100){if(diameter==''){radius=100;diameter=200}
if(diameter>300){radius=150;diameter=300}
if(diameter<100){radius=50;diameter=100}}else{radius=diameter/2}
if(diagramWidth=='')diagramWidth=10;if(diagramWidth>radius)diagramWidth=10;if(diagramWidth<1)diagramWidth=1;if(window.devicePixelRatio>=2){var oldSize=diameter;radius=radius*2;diameter=diameter*2;diagramWidth=diagramWidth*2}
var correction=+diagramWidth/2;var dataArray=[data1,data2,data3,data4];for(var i=0;i<4;i++){if(dataArray[i]!=''&&blocksNumber>i){var canvas=rec.querySelector('.t505__pie'+(i+1));canvas.setAttribute('width',diameter);canvas.setAttribute('height',diameter);var context=canvas.getContext('2d');if(window.devicePixelRatio>=2){canvas.style.width=oldSize+'px';canvas.style.height=oldSize+'px'}
for(var j=0;j<2;j++){if(j===1&&dataArray[i]==0)continue;if(j==0){context.strokeStyle=pieBgColor;var angle=Math.PI*2;context.lineWidth=diagramWidth-1}else{context.strokeStyle=sectorColor;var angle=Math.PI*2*(dataArray[i]/100);context.lineWidth=diagramWidth}
context.beginPath();context.lineCap='round';context.moveTo(diameter-correction,radius);context.arc(radius,radius,radius-correction,0,angle,!1);context.stroke()}}}}
function t531_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t531');if(!container)return;var images=rec.querySelectorAll('.t531__blockimg');if(!images[0])return;var imageWidth=images[0].getAttribute('data-image-width');var imageHeight=images[0].getAttribute('data-image-height');var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;for(var i=0;i<images.length;i++){images[i].style.paddingBottom=imagePadding+'%'}
if(window.innerWidth>480){var textWrappers=rec.querySelectorAll('.t531__textwrapper');var imageWrapperHeight=rec.querySelector('.t531__imgwrapper').clientHeight;for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height=imageWrapperHeight+'px'}}}
function t552_init(recid,ratio){var rec=document.getElementById('rec'+recid);if(!rec)return;var recordBlock=rec?rec.querySelector('.t552'):null;t552__setHeight(recid,ratio);window.addEventListener('resize',t_throttle(function(){t552__setHeight(recid,ratio)}));if(typeof jQuery!=='undefined'){$(recordBlock).on('displayChanged',function(){t552__setHeight(recid,ratio)})}else{if(recordBlock){recordBlock.addEventListener('displayChanged',function(){t552__setHeight(recid,ratio)})}}}
function t552__setHeight(recid,ratio){var rec=document.getElementById('rec'+recid);if(!rec)return;var firstIMG=rec.querySelector('.t552__blockimg');var images=rec.querySelectorAll('.t552__blockimg');Array.prototype.forEach.call(images,function(img){var calculatedHeight=Math.floor(firstIMG.offsetWidth*ratio);img.style.height=calculatedHeight+'px'})}
function t604_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;t604_imageHeight(recid);t604_arrowWidth(recid);t604_show(recid);t604_hide(recid);window.addEventListener('resize',t_throttle(function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)}));if(typeof jQuery!=='undefined'){$(rec).find('.t604').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}else{var currentBlock=rec.querySelector('.t604');if(currentBlock){currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}}}
function t604_show(recid){var rec=document.getElementById('rec'+recid);var playBtns=rec.querySelectorAll('.t604__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var parent=play.parentElement;var videoBg=parent?parent.querySelector('.t-slds__bgimg'):null;if(videoBg)videoBg.style.opacity='0';var sliderVideo=play.getAttribute('data-slider-video-type');var url=play.getAttribute('data-slider-video-url');var nextEl=play.nextElementSibling;if(nextEl)nextEl.style.zIndex='3';var iframe;switch(sliderVideo){case 'youtube':iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break;case 'vimeo':var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'?autoplay=1&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break}})})}
function t604_hide(recid){var rec=document.getElementById('rec'+recid);var frames=rec.querySelectorAll('.t604__frame');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(frames,function(frame){frame.innerHTML='';frame.style.zIndex=''})})}
function t604_imageHeight(recid){var rec=document.getElementById('rec'+recid);var images=rec.querySelectorAll('.t604__separator');Array.prototype.forEach.call(images,function(image){var imgHeight=image.getAttribute('data-slider-image-height');var imgWidth=image.getAttribute('data-slider-image-width');var imgRatio=imgHeight/imgWidth;var imgPadding=imgRatio*100;image.style.paddingBottom=imgPadding+'%'})}
function t604_arrowWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var arrows=rec.querySelectorAll('.t-slds__arrow_wrapper');var slide=rec.querySelector('.t-slds__wrapper');var slideWidth=slide?slide.offsetWidth:0;var arrowWidth=window.innerWidth-slideWidth;Array.prototype.forEach.call(arrows,function(arrow){arrow.style.width=window.innerWidth>960?(arrowWidth/2)+'px':''})}
function t668_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t668');if(!container)return;var accordion=rec.querySelectorAll('.t668__accordion')[0];var headers=rec.querySelectorAll('.t668__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var contentStyle=getComputedStyle(rec.querySelector('.t668__content'),null);var oldStyle={paddingTop:contentStyle.paddingTop,paddingBottom:contentStyle.paddingBottom};var zeroBlocks=document.querySelectorAll('.t396');var event=document.createEvent('Event');if(accordion){accordion=accordion.getAttribute('data-accordion')}else{accordion='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;Array.prototype.forEach.call(zeroBlocks,function(zero){event.initEvent('displayChanged',!0,!0);zero.dispatchEvent(event)});if(element.classList.contains('t668__opened')){element.classList.remove('t668__opened');t668_accordionHide(container)}else{if(accordion==='true'){t668_accordionAllHide(headers)}
element.classList.add('t668__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';container.setAttribute('style',t668_addStyle(container)+' padding-top: '+oldStyle.paddingTop+'; padding-bottom: '+oldStyle.paddingBottom+';')},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t668_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t668__opened');t668_accordionHide(elementHide.nextElementSibling)}}
function t668_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight=0;container.setAttribute('style',t668_addStyle(container)+' padding-top: 0px !important; padding-bottom: 0px !important;')},0)}
function t668_addStyle(container){var attrStyle=container.getAttribute('style');var arrStyle=attrStyle.split(';');var newArr=[];for(var i=0;i<arrStyle.length;i++){var style=arrStyle[i];if(style.indexOf('padding-top')===-1&&style.indexOf('padding-bottom')===-1){newArr.push(style)}}
return newArr.join(';')}
function t678_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t678__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t678__fadeOut(tildaLabel,50)}},300)}else{t678__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t678__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t678__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t678__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t678__easeInOutCubic(currentTime,change){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t678__animateScroll(){currentTime+=increment;window.scrollTo(0,t678__easeInOutCubic(currentTime,change));if(currentTime<duration){setTimeout(t678__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t678__animateScroll()}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t702_resizePopup(recId);t702__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup()});popupCloseBtn.addEventListener('click',t702_closePopup);if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var range=rec.querySelector('.t-range');var documentBody=document.body;popup.style.display='block';if(range)t702__triggerEvent(range,'popupOpened');setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
document.addEventListener('keydown',t702_escClosePopup);t702__lazyLoad()}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup()}
function t702_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t702__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t702_escClosePopup)}
function t702_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t702__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t702__fadeOut(tildaLabel)}},300)}else{t702__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t702__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t702__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t702__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t702__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t702__animateScroll(){currentTime+=increment;window.scrollTo(0,t702__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t702__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t702__animateScroll()}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t764_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderContainer=rec.querySelector('.t-slds__container');var sliderWidth=sliderContainer?sliderContainer.offsetWidth:0;var sliderPos=sliderWrapper?sliderWrapper.getAttribute('data-slider-pos'):'0';var pos=parseFloat(sliderPos);if(sliderWrapper)sliderWrapper.style.transform='translate3d(-'+(sliderWidth*pos)+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)});var currentBlock=rec.querySelector('.t764');if(currentBlock){if(typeof jQuery!=='undefined'){$('.t764').on('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}else{currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}}}
function t814_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t814');if(!container)return;t814_setHeight(recId);window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t814_setHeight(recId)}));if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t814_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t814_setHeight(recId)})}}
function t814_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t814');if(!container)return;var blockTextWrap=rec.querySelector('.t814__blocktext-wrapper');var textWrapper=rec.querySelector('.t814__blocktext');var image=rec.querySelector('.t814__blockimg');var imageStyle=getComputedStyle(image,null);var imagePaddingTop=parseInt(imageStyle.paddingTop)||0;var imagePaddingBottom=parseInt(imageStyle.paddingBottom)||0;var imageHeight=image.clientHeight-(imagePaddingTop+imagePaddingBottom);if(window.innerWidth>960){textWrapper.style.height=imageHeight+'px';blockTextWrap.style.height=t814_outerHeight(textWrapper)+'px'}else{blockTextWrap.style.height='auto'}}
function t814_outerHeight(element){var height=element.offsetHeight;var style=getComputedStyle(element);height+=parseInt(style.marginTop)+parseInt(style.marginBottom);return height}
function t817_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');var tabs=rec.querySelectorAll('.t817__tab');var select=rec.querySelector('.t817__select');var content=rec.querySelectorAll('.t817__content');if(!tabs.length)return;if(!content.length)return;if(currentMode!=='edit'&&currentMode!=='preview'){t817_scrollToTabs(recid);window.onload=function(){t817_scrollToTabs(recid)}}
t817_showTabByUrl(recid,tabs,content,select);t817_showTab(recid,tabs,content,currentMode);t817_showTabMobile(recid,select,content,currentMode)}
function t817_showTab(recid,tabs,content,currentMode){Array.prototype.forEach.call(tabs,function(tabItem){tabItem.addEventListener('click',function(event){var tabNumber=this.getAttribute('data-tab-number');Array.prototype.forEach.call(tabs,function(tabItem){tabItem.classList.remove('t817__tab_active')});Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t817__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumber,10)){contentItem.classList.add('t817__content_active')}});tabItem.classList.add('t817__tab_active');t817_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
event.preventDefault()})})}
function t817_showTabMobile(recid,select,content,currentMode){select.addEventListener('change',function(event){var tabNumberMobile=this.value;Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t817__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumberMobile,10)){contentItem.classList.add('t817__content_active')}});t817_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
event.preventDefault()})}
function t817_showTabByUrl(recid,tabs,content,select){var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf(recid+'-');var tabIndex=currentUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!==-1){Array.prototype.forEach.call(tabs,function(tabItem){if(parseInt(tabItem.getAttribute('data-tab-number'),10)===parseInt(tabIndex,10)){tabItem.classList.add('t817__tab_active')}});Array.prototype.forEach.call(content,function(contentItem){if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabIndex,10)){contentItem.classList.add('t817__content_active')}});select.value=tabIndex}else{tabs[0].classList.add('t817__tab_active');content[0].classList.add('t817__content_active')}}
function t817_scrollToTabs(recid){var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf('#!/tab/');var tabIndexNumberStart=currentUrl.indexOf('tab/');if(parseInt(tabIndexNumber,10)!==-1){var tabRecord=currentUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(parseInt(tabRecord,10)===parseInt(recid,10)){var tabBlock=document.querySelector('#rec'+tabRecord).querySelector('.t817');var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;if(window.innerWidth>960){var target=targetOffset-200}else{var target=targetOffset-100}
t817_scrollToEl(target,300)}}}
function t817_removeUrl(){var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tab/')}
currentUrl=currentUrl.substring(0,indexToRemove);if(parseInt(indexToRemove,10)!==-1){if(typeof history.replaceState==='function'){window.history.replaceState('','',currentUrl)}}}
function t817_scrollToEl(elTopPos,duration){if(elTopPos===window.pageYOffset)return!1;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(10*(elTopPos||window.pageYOffset))/duration;var timer=setInterval(function(){if(cashedDiff>elTopPos){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>elTopPos&&window.pageYOffset<=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}else if(cashedDiff<=elTopPos&&window.pageYOffset>=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10);var timer2=setTimeout(function(){clearInterval(timer);document.body.removeAttribute('data-scrollable');clearTimeout(timer2)},duration*2)}
function t819_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');var tabs=rec.querySelectorAll('.t819__tab');var select=rec.querySelector('.t819__select');var content=rec.querySelectorAll('.t819__content');if(!tabs.length)return;if(!content.length)return;if(currentMode!=='edit'&&currentMode!=='preview'){t819_scrollToTabs(recid);window.onload=function(){t819_scrollToTabs(recid)}}
t819_showTabByUrl(recid,tabs,content,select);t819_showTab(recid,tabs,content,currentMode);t819_showTabMobile(recid,select,content,currentMode)}
function t819_showTab(recid,tabs,content,currentMode){Array.prototype.forEach.call(tabs,function(tabItem){tabItem.addEventListener('click',function(event){var tabNumber=this.getAttribute('data-tab-number');Array.prototype.forEach.call(tabs,function(tabItem){tabItem.classList.remove('t819__tab_active')});Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t819__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumber,10)){contentItem.classList.add('t819__content_active')}});tabItem.classList.add('t819__tab_active');t819_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
event.preventDefault()})})}
function t819_showTabMobile(recid,select,content,currentMode){select.addEventListener('change',function(event){var tabNumberMobile=this.value;Array.prototype.forEach.call(content,function(contentItem){contentItem.classList.remove('t819__content_active');if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabNumberMobile,10)){contentItem.classList.add('t819__content_active')}});t819_removeUrl();if(currentMode!=='edit'&&currentMode!=='preview'){if(typeof history.replaceState==='function'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(!currentMode){if(window.lazy==='y'||document.querySelector('#allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
event.preventDefault()})}
function t819_showTabByUrl(recid,tabs,content,select){var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf(recid+'-');var tabIndex=currentUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!==-1){Array.prototype.forEach.call(tabs,function(tabItem){if(parseInt(tabItem.getAttribute('data-tab-number'),10)===parseInt(tabIndex,10)){tabItem.classList.add('t819__tab_active')}});Array.prototype.forEach.call(content,function(contentItem){if(parseInt(contentItem.getAttribute('data-tab-content-number'),10)===parseInt(tabIndex,10)){contentItem.classList.add('t819__content_active')}});select.value=tabIndex}else{tabs[0].classList.add('t819__tab_active');content[0].classList.add('t819__content_active')}}
function t819_scrollToTabs(recid){var currentUrl=window.location.href;var tabIndexNumber=currentUrl.indexOf('#!/tab/');var tabIndexNumberStart=currentUrl.indexOf('tab/');if(parseInt(tabIndexNumber,10)!==-1){var tabRecord=currentUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(parseInt(tabRecord,10)===parseInt(recid,10)){var tabBlock=document.querySelector('#rec'+tabRecord).querySelector('.t819');var targetOffset=tabBlock.getBoundingClientRect().top+window.pageYOffset;if(window.innerWidth>960){var target=targetOffset-200}else{var target=targetOffset-100}
t819_scrollToEl(target,300)}}}
function t819_removeUrl(){var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tab/')}
currentUrl=currentUrl.substring(0,indexToRemove);if(parseInt(indexToRemove,10)!==-1){if(typeof history.replaceState==='function'){window.history.replaceState('','',currentUrl)}}}
function t819_scrollToEl(elTopPos,duration){if(elTopPos===window.pageYOffset)return!1;var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(10*(elTopPos||window.pageYOffset))/duration;var timer=setInterval(function(){if(cashedDiff>elTopPos){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>elTopPos&&window.pageYOffset<=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}else if(cashedDiff<=elTopPos&&window.pageYOffset>=elTopPos){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10);var timer2=setTimeout(function(){clearInterval(timer);document.body.removeAttribute('data-scrollable');clearTimeout(timer2)},duration*2)}
function t851_init(recId){t851_updateLazyLoad(recId)}
function t851_updateLazyLoad(recId){var scrollContainer=document.querySelector('#rec'+recId+' .t851__container_mobile-flex');var allRecords=document.getElementById('allrecords');var currentMode=allRecords.getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}}
function t856_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t856');if(!container)return;setTimeout(function(){t856_setHeight(recId);t856_updateLazyLoad(recId)},500);window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t856_setHeight(recId)}));if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t856_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t856_setHeight(recId)})}
if(container&&container.classList.contains('t856__previewmode')){setInterval(function(){t856_setHeight(recId)},5000)}}
function t856_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t856');if(!container)return;var ratio=container.getAttribute('data-tile-ratio');var rows=rec.querySelectorAll('.t856__row');var col=rec.querySelector('.t856__col');var ratioHeight=0;if(col){ratioHeight=parseFloat(getComputedStyle(col,null).width)*ratio}
for(var i=0;i<rows.length;i++){var row=rows[i];var largestHeight=0;var tables=row.querySelectorAll('.t856__table');for(var j=0;j<tables.length;j++){var table=tables[j];var textHeight=table.querySelector('.t856__textwrapper').offsetHeight;if(table.querySelector('.t856__cell').classList.contains('t856__button-bottom')){textHeight+=table.querySelector('.t856__button-container').offsetHeight}
if(textHeight>largestHeight)largestHeight=textHeight}
if(window.innerWidth>=960){if(largestHeight>ratioHeight){for(var j=0;j<tables.length;j++){tables[j].style.height=largestHeight+'px';tables[j].style.minHeight='auto'}}else{for(var j=0;j<tables.length;j++){tables[j].style.height=ratioHeight+'px';tables[j].style.minHeight='auto'}}}else{for(var j=0;j<tables.length;j++){tables[j].style.minHeight=ratioHeight+'px';tables[j].style.height=null}}
if(t856_GetIEVersion()>0){var currentRowHeight=getComputedStyle(row.querySelector('.t856__table')).height;row.querySelector('.t856__bg').style.height=currentRowHeight+'px';row.querySelector('.t856__overlay').style.height=currentRowHeight+'px'}}}
function t856_GetIEVersion(){var userAgent=window.navigator.userAgent;var index=userAgent.indexOf('MSIE');if(index>0){return parseInt(userAgent.substring(index+5,userAgent.indexOf('.',index)))}else if(!!navigator.userAgent.match(/Trident\/7\./)){return 11}else{return 0}}
function t856_updateLazyLoad(recId){var scrollContainer=document.querySelector('#rec'+recId+' .t856__container_mobile-flex');var allRecords=document.getElementById('allrecords');var currentMode=allRecords.getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}}
function t868_setHeight(rec){var videoCarier=rec.querySelector('.t868__video-carier');if(videoCarier){var paddingLeft=parseInt(videoCarier.style.paddingLeft,10)||0;var paddingRight=parseInt(videoCarier.style.paddingRight,10)||0;var ratio16to9=0.5625;var height=videoCarier.clientWidth-(paddingLeft+paddingRight)*ratio16to9;videoCarier.style.height=height;Array.prototype.forEach.call(videoCarier.closest,function(parent){parent.style.height=height})}}
function t868_initPopup(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');if(!popup)return;var hook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var customCodeHTML=t868__readCustomCode(rec);if(hook){var allRecs=document.querySelectorAll('.r');Array.prototype.forEach.call(allRecs,function(recR){var buttons=recR.querySelectorAll('a[href="'+hook+'"]');Array.prototype.forEach.call(buttons,function(button){button.addEventListener('click',function(event){t868_showPopup(rec,customCodeHTML);t868_resizePopup(rec);event.preventDefault();if(analitics){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})})})}}
function t868__readCustomCode(rec){var codeWrap=rec.querySelector('.t868 .t868__code-wrap');if(!codeWrap)return;var customCode=codeWrap.innerHTML;if(codeWrap.parentNode){codeWrap.parentNode.removeChild(codeWrap)}
return customCode}
function t868_showPopup(rec,customCodeHTML){var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');if(!popupContainer)return;popupContainer.innerHTML=customCodeHTML;popup.style.display='block';t868_setHeight(rec);setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},100);document.querySelector('body').classList.add('t-body_popupshowed');popup.addEventListener('click',function(event){var container;if(event.target){container=event.target.closest('.t-popup__container')}
if(!container){t868_closePopup(rec)}});var closeButton=rec.querySelector('.t-popup__close');if(closeButton){closeButton.addEventListener('click',function(){t868_closePopup(rec)})}
Array.prototype.forEach.call(rec.querySelectorAll('a[href*="#"]'),function(linkItem){linkItem.addEventListener('click',function(){var url=linkItem.getAttribute('href');if(url.indexOf('#order')!==-1){var popupContainer=rec.querySelector('.t-popup__container');setTimeout(function(){while(popupContainer.firstChild){popupContainer.removeChild(popupContainer.firstChild)}},600)}
if(!url||url.substring(0,7)!=='#price:'){t868_closePopup(rec);if(!url||url.substring(0,7)==='#popup:'){setTimeout(function(){document.querySelector('body').classList.add('t-body_popupshowed')},300)}}})});document.addEventListener('keydown',function(event){if(event.keyCode===27){t868_closePopup(rec)}})}
function t868_closePopup(rec){var popupContainer=rec.querySelector('.t-popup__container');document.querySelector('body').classList.remove('t-body_popupshowed');rec.querySelector('.t-popup').classList.remove('t-popup_show');while(popupContainer.firstChild){popupContainer.removeChild(popupContainer.firstChild)}
setTimeout(function(){var popup=rec.querySelector('.t-popup');if(!popup.classList.contains('.t-popup_show')){popup.style.display='none'}},300)}
function t868_resizePopup(rec){var popupContainer=rec.querySelector('.t-popup__container');var paddingTop=parseInt(popupContainer.style.paddingTop,10)||0;var paddingBottom=parseInt(popupContainer.style.paddingBottom,10)||0;var popupContainerHeight=popupContainer.clientHeight-(paddingTop+paddingBottom);var viewPort=window.innerHeight;if(popupContainerHeight>viewPort){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t923_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t923');if(!container)return;t923_unifyHeights(recId);window.addEventListener('resize',t_throttle(function(){t923_unifyHeights(recId)}));if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t923_unifyHeights(recId)})}else{container.addEventListener('displayChanged',function(){t923_unifyHeights(recId)})}
window.addEventListener('load',function(){t923_unifyHeights(recId)})}
function t923_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t923');if(!container)return;var cols=rec.querySelectorAll('.t923__content');var maxHeight=0;for(var i=0;i<cols.length;i++){cols[i].style.height=''}
for(var i=0;i<cols.length;i++){var col=cols[i];var colText=col.querySelector('.t923__textwrapper');var colBtn=col.querySelectorAll('.t923__btn-wrapper, .t923__btntext-wrapper')[0];var colHeight=colText.offsetHeight+(colBtn?colBtn.offsetHeight:0);if(colHeight>maxHeight)maxHeight=colHeight}
for(var i=0;i<cols.length;i++){cols[i].style.height=maxHeight+'px'}
t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recId)})}