function t121_setHeight(recid){var rec=document.getElementById('rec'+recid);var videoBlock=document.getElementById('youtubeiframe'+recid);var videoParent=videoBlock?videoBlock.parentNode:null;var videoWidth=videoBlock?videoBlock.offsetWidth:0;var videoHeight=videoWidth*0.5625;if(videoBlock)videoBlock.style.height=videoHeight+'px';if(videoParent)videoParent.style.height=videoHeight+'px';var videoLazy=rec?rec.querySelector('.t-video-lazyload'):null;if(videoLazy){var iframeLazy=videoLazy.querySelector('iframe');var heightLazy=videoLazy.offsetWidth*0.5625;videoLazy.style.height=heightLazy+'px';if(iframeLazy)iframeLazy.style.height=heightLazy+'px';setTimeout(function(){videoBlock=document.getElementById('youtubeiframe'+recid);videoWidth=videoBlock?videoBlock.offsetWidth:0;if(videoBlock)videoBlock.style.height=(videoWidth*0.5625)+'px'},200)}}
function t142_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t142__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom)+5;var textHeight=button.scrollHeight;if(buttonHeight<textHeight){button.classList.add('t142__submit-overflowed')}}
function t190_scrollToTop(){var duration=700;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=0-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t190__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t190__animateScroll(){currentTime+=increment;window.scrollTo(0,t190__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t190__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t190__animateScroll()}
function t270_scroll(hash,offset,speed){if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var root=$('html, body');var target="";if(speed===undefined){speed=400}
try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
var isHistoryChangeAllowed=window.location.hash!==hash;var complete=function(){if(!isHistoryChangeAllowed){return}
if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
var dontChangeHistory=Boolean($('.t270').attr('data-history-disabled'));if(dontChangeHistory){complete=function(){}}
root.animate({scrollTop:target.offset().top-offset},speed,complete);return!0}
function t393_appearMenu(recId){if(window.innerWidth>980){var recs=document.querySelectorAll('.t393');var scrollTop=window.pageYOffset;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);for(var i=0;i<recs.length;i++){var rec=recs[i];var appearOffset=rec.getAttribute('data-appearoffset');var hideOffset=rec.getAttribute('data-hideoffset');if(appearOffset){if(appearOffset.indexOf('vh')>-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);if(scrollTop>=appearOffset){if(rec.style.visibility==='hidden'){rec.style.visibility='visible';t393__fadeIn(rec)}}else{rec.style.visibility='hidden'}}
if(hideOffset){if(hideOffset.indexOf('vh')>-1){hideOffset=Math.floor((window.innerHeight*(parseInt(hideOffset)/100)))}
hideOffset=parseInt(hideOffset,10);if(scrollTop+window.innerHeight>=documentHeight-hideOffset){if(rec.style.visibility!=='hidden'){rec.style.visibility='hidden'}}else if(appearOffset){if(scrollTop>=appearOffset){rec.style.visibility='visible'}}else{rec.style.visibility='visible'}}}}}
function t393__fadeIn(el){if(el.style.display==='block')return;var opacity=0;el.style.opacity=opacity;el.style.display='block';var timer=setInterval(function(){el.style.opacity=opacity;opacity+=0.1;if(opacity>=1.0){clearInterval(timer);el.style.display=''}},30)}
function t396_init(recid){var data='';var resolution=t396_detectResolution();var allRecords=document.getElementById('allrecords');var record=document.getElementById('rec'+recid);var zeroBlock=record?record.querySelector('.t396'):null;var artBoard=record?record.querySelector('.t396__artboard'):null;window.tn_window_width=document.documentElement.clientWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;t396_initTNobj();t396_switchResolution(resolution);t396_updateTNobj();t396_artboard_build(data,recid);window.addEventListener('resize',function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if(window.isMobile){if(document.documentElement.clientWidth!==window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});window.addEventListener('orientationchange',function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});window.addEventListener('load',function(){t396_allelems__renderView(artBoard);var blockOverflow=artBoard?window.getComputedStyle(artBoard).getPropertyValue('overflow'):'';if(typeof t_lazyload_update==='function'&&blockOverflow==='auto'&&artBoard){artBoard.addEventListener('scroll',t_throttle(function(){var dataLazy=allRecords?allRecords.getAttribute('data-tilda-lazy'):null;if(window.lazy==='y'||dataLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&blockOverflow==='visible'){if(artBoard)artBoard.style.overflow='hidden';setTimeout(function(){if(artBoard)artBoard.style.overflow='visible'},1)}});if(record&&zeroBlock&&artBoard&&record.getAttribute('data-connect-with-tab')==='yes'){zeroBlock.addEventListener('displayChanged',function(){t396_allelems__renderView(artBoard)})}
if(window.isSafari&&zeroBlock){zeroBlock.classList.add('t396_safari')}
var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':null;if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search('Firefox')!==-1;var isOpera=(!!window.opr&&!!window.opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')!==-1;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var resolution=t396_detectResolution();var record=document.getElementById('rec'+recid);var zeroBlockElements=record?record.querySelectorAll('.t396__elem'):[];var artBoard=record?record.querySelector('.t396__artboard'):null;if(artBoard){var artBoardWidth=artBoard.clientWidth;var updatedBlockHeight=Math.floor(artBoard.clientHeight*window.tn_scale_factor);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;if(artBoardHeightVH){var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var scaledMinHeight=artBoardMinHeight*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=artBoardMaxHeight)?scaledMinHeight:artBoardMaxHeight}
artBoard.classList.add('t396__artboard_scale');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'</style>';artBoard.insertAdjacentHTML('beforeend',styleStr)}
Array.prototype.forEach.call(zeroBlockElements,function(zeroBlockElement){var atom=zeroBlockElement.querySelector('.tn-atom');var containerProp=t396_elem__getFieldValue(zeroBlockElement,'container');if(containerProp==='grid'){if(isOnlyScalable){if(atom){var atomParent=atom.parentNode;var div=document.createElement('div');div.classList.add('tn-atom__scale-wrapper');div.style.transform='scale('+window.tn_scale_factor+')';if(atomParent)atomParent.removeChild(atom);div.appendChild(atom);if(atomParent)atomParent.appendChild(div)}}else{zeroBlockElement.style.zoom=window.tn_scale_factor;if(zeroBlockElement.getAttribute('data-elem-type')==='text'&&resolution<1200&&atom){atom.style.webkitTextSizeAdjust='auto'}
if(atom)atom.style.transformOrigin='center'}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var resolution=t396_detectResolution();var scaleStyle=record?record.querySelector('.t396__scale-style'):null;t396_removeElementFromDOM(scaleStyle);if(!isOnlyScalable){var elements=record?record.querySelectorAll('.t396__elem'):[];Array.prototype.forEach.call(elements,function(element){element.style.zoom='';var atom=element.querySelector('.tn-atom');if(atom)atom.style.transformOrigin=''})}else{var atoms=record.querySelectorAll('.tn-atom');Array.prototype.forEach.call(atoms,function(atom){var atomWrapper=atom.closest('.tn-atom__scale-wrapper');var atomParent=atomWrapper?atomWrapper.parentNode:null;if(atomParent)atomParent.removeChild(atomWrapper);if(atomParent)atomParent.appendChild(atom)})}
var artBoard=record?record.querySelector('.t396__artboard'):null;var artBoardWidth=artBoard?artBoard.clientWidth:0;window.tn_window_width=window.isMobile?document.documentElement.clientWidth:window.innerWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;t396_switchResolution(resolution);t396_updateTNobj();t396_ab__renderView(artBoard);t396_allelems__renderView(artBoard);var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';if(isScaled&&tildaMode!=='edit')t396_scaleBlock(recid)}
function t396_detectResolution(){var windowWidth=window.isMobile?document.documentElement.clientWidth:window.innerWidth;var resolution=1200;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length-1;i++){if(windowWidth<breakpoints[i]){resolution=breakpoints[i+1]}}
return resolution}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=['320','480','640','960','1200'];window.tn.canvas_max_sizes=['480','640','960','1200',''];window.tn.ab_fields=['height','width','bgcolor','bgimg','bgattachment','bgposition','filteropacity','filtercolor','filteropacity2','filtercolor2','height_vh','valign']}
function t396_updateTNobj(){tn_console('func: updateTNobj');var allRecords=document.getElementById('allrecords');var allRecPaddingLeft=allRecords?window.getComputedStyle(allRecords).paddingLeft||'0':'0';allRecPaddingLeft=parseInt(allRecPaddingLeft,10);var allRecPaddingRight=allRecords?window.getComputedStyle(allRecords).paddingRight||'0':'0';allRecPaddingRight=parseInt(allRecPaddingRight,10);if(window.zero_window_width_hook&&window.zero_window_width_hook==='allrecords'&&allRecords){window.tn.window_width=allRecords.clientWidth-(allRecPaddingLeft+allRecPaddingRight)}else{window.tn.window_width=document.documentElement.clientWidth}
window.tn.window_height=document.documentElement.clientHeight;window.tn.curResolution;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length;i++){if(+window.tn.curResolution===breakpoints[i]){window.tn.canvas_min_width=breakpoints[i];window.tn.canvas_max_width=i===0?window.tn.window_width:breakpoints[i-1]}}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=(window.tn.window_width-window.tn.grid_width)/2}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId='Don\'t call this twice without a uniqueId'}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(resolution,resolutionMax){tn_console('func: switchResolution');if(typeof resolutionMax==='undefined'){var breakpoints=[1200,960,640,480,320];breakpoints.forEach(function(breakpoint,i){if(+resolution===breakpoint){resolutionMax=i===0?'':breakpoints[i-1]}})}
window.tn.curResolution=resolution;window.tn.curResolution_max=resolutionMax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var artBoard=record?record.querySelector('.t396__artboard'):null;if(!artBoard)return!1;t396_ab__renderView(artBoard);var elements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(elements,function(element){var dataType=element.getAttribute('data-elem-type');switch(dataType){case 'text':t396_addText(artBoard,element);break;case 'image':t396_addImage(artBoard,element);break;case 'shape':t396_addShape(artBoard,element);break;case 'button':t396_addButton(artBoard,element);break;case 'video':t396_addVideo(artBoard,element);break;case 'html':t396_addHtml(artBoard,element);break;case 'tooltip':t396_addTooltip(artBoard,element);break;case 'form':t396_addForm(artBoard,element);break;case 'gallery':t396_addGallery(artBoard,element);break}});artBoard.classList.remove('rendering');artBoard.classList.add('rendered');var artBoardOverflow=artBoard.getAttribute('data-artboard-ovrflw');if((artBoardOverflow==='visible'||artBoardOverflow==='visibleX')&&allRecords){allRecords.style.overflow='hidden'}
if(window.isMobile){var style=document.createElement('style');style.textContent='@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}';record.insertAdjacentElement('beforeend',style)}}
function t396_ab__renderView(artBoard){if(!artBoard)return!1;var fields=window.tn.ab_fields;var allRecords=document.getElementById('allrecords');var artBoardHeightVH;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(artBoard,fields[i])}
var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':!1;var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
var offsetTop;if(artBoardMinHeight===artBoardMaxHeight||(scaledMinHeight&&scaledMinHeight>=artBoardMaxHeight)){offsetTop=0}else{var artBoardVerticalAlign=t396_ab__getFieldValue(artBoard,'valign');switch(artBoardVerticalAlign){case 'top':offsetTop=0;break;case 'center':if(scaledMinHeight){offsetTop=parseFloat(((artBoardMaxHeight-scaledMinHeight)/2).toFixed(1))}else{offsetTop=parseFloat(((artBoardMaxHeight-artBoardMinHeight)/2).toFixed(1))}
break;case 'bottom':if(scaledMinHeight){offsetTop=parseFloat((artBoardMaxHeight-scaledMinHeight).toFixed(1))}else{offsetTop=parseFloat((artBoardMaxHeight-artBoardMinHeight).toFixed(1))}
break;case 'stretch':offsetTop=0;artBoardMinHeight=artBoardMaxHeight;break;default:offsetTop=0;break}}
artBoard.setAttribute('data-artboard-proxy-min-offset-top',offsetTop);artBoard.setAttribute('data-artboard-proxy-min-height',artBoardMinHeight);artBoard.setAttribute('data-artboard-proxy-max-height',artBoardMaxHeight);var filter=artBoard.querySelector('.t396__filter');var carrier=artBoard.querySelector('.t396__carrier');artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');artBoardHeightVH=parseFloat(artBoardHeightVH);if(window.isMobile&&artBoardHeightVH){var height=document.documentElement.clientHeight*artBoardHeightVH/100;artBoard.style.height=height+'px';if(filter)filter.style.height=height+'px';if(carrier)carrier.style.height=height+'px'}}
function t396_addText(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addText');var fieldsString='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addImage(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addImage');var fieldsString='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var images=element.querySelectorAll('img');Array.prototype.forEach.call(images,function(img){img.addEventListener('load',function(){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}});if(img.complete){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}}
img.addEventListener('tuwidget_done',function(){t396_elem__renderViewOneField(element,'top')})})}
function t396_addShape(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addShape');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addButton(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addButton');var fieldsString='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);return(element)}
function t396_addVideo(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addVideo');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var videoEl=element.querySelector('.tn-atom__videoiframe');var atom=element.querySelector('.tn-atom');if(atom)atom.style.backgroundColor='#000';var videoCover=atom?atom.getAttribute('data-atom-video-has-cover'):'';if(!videoCover)videoCover='';if(videoCover==='y'&&atom){atom.addEventListener('click',function(){var iframe=videoEl?videoEl.querySelector('iframe'):null;var dataOriginal=iframe?iframe.getAttribute('data-original'):'';if(iframe)iframe.setAttribute('src',dataOriginal);atom.style.backgroundImage='none';var playBtn=atom.querySelector('.tn-atom__video-play-link');if(playBtn)playBtn.style.display='none'})}
var allRecords=document.getElementById('allrecords');var autoplay=t396_elem__getFieldValue(element,'autoplay');var showinfo=t396_elem__getFieldValue(element,'showinfo');var loop=t396_elem__getFieldValue(element,'loop');var mute=t396_elem__getFieldValue(element,'mute');var startSec=t396_elem__getFieldValue(element,'startsec');var endSec=t396_elem__getFieldValue(element,'endsec');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var url='';var script=document.createElement('script');script.textContent='lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});';var youtubeID=videoEl?videoEl.getAttribute('data-youtubeid'):'';if(youtubeID){url='//youtube.com/embed/';url+=youtubeID+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo==='y'?'1':'0');if(loop==='y'){url+='&loop=1&playlist='+youtubeID}
if(startSec>0){url+='&start='+startSec}
if(endSec>0){url+='&end='+endSec}
if(mute==='y'){url+='&mute=1'}
if(videoCover==='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
videoEl.innerHTML='<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){element.insertAdjacentElement('beforeend',script)}
if(autoplay==='y'&&mute==='y'){atom.click()}}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>'}}}
var vimeoID=videoEl?videoEl.getAttribute('data-vimeoid'):'';if(vimeoID){url='//player.vimeo.com/video/';url+=vimeoID+'?color=ffffff&badge=0';if(showinfo==='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop==='y'){url+='&loop=1'}
if(mute==='y'){url+='&muted=1'}
if(videoCover==='y'){url+='&autoplay=1';videoEl.innerHTML='<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}}}}
function t396_addHtml(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addHtml');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addTooltip(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addTooltip');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var tooltip=element.querySelector('.tn-atom__pin');var tooltipContent=element.querySelector('.tn-atom__tip');var tooltipOpenTrigger=element.getAttribute('data-field-tipopen-value');if(window.isMobile||tooltipOpenTrigger==='click'){t396_setUpTooltip_mobile(element,tooltip,tooltipContent)}else{t396_setUpTooltip_desktop(element,tooltip,tooltipContent)}
setTimeout(function(){var atomImages=document.querySelectorAll('.tn-atom__tip-img');Array.prototype.forEach.call(atomImages,function(img){var imgOriginal=img.getAttribute('data-tipimg-original');if(imgOriginal)img.src=imgOriginal})},3000)}
function t396_addForm(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,top,left,';fieldsString+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addGallery(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,height,top,left,';fieldsString+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_elem__setFieldValue(element,prop,val,flag_render,flag_updateui,resolution){element=t396_getEl(element);if(!element)return;if(!resolution)resolution=window.tn.curResolution;if(+resolution<1200&&prop!=='zindex'){element.setAttribute('data-field-'+prop+'-res-'+resolution+'-value',val)}else{element.setAttribute('data-field-'+prop+'-value',val)}
if(flag_render==='render')elem__renderViewOneField(element,prop);if(flag_updateui==='updateui')panelSettings__updateUi(element,prop,val)}
function t396_elem__getFieldValue(element,prop){element=t396_getEl(element);if(!element)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=element.getAttribute('data-field-'+prop+'-value')}
if(i>0&&+resolution===breakpoint){dataField=element.getAttribute('data-field-'+prop+'-res-'+breakpoint+'-value');if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=element.getAttribute('data-field-'+prop+'-res-'+slicedBreakpoints[n]+'-value');if(dataField)break}}
if(!dataField)dataField=element.getAttribute('data-field-'+prop+'-value')}});return dataField?dataField:''}
function t396_elem__renderView(element){element=t396_getEl(element);tn_console('func: elem__renderView');var fields=element?element.getAttribute('data-fields'):'';if(!fields)return!1;fields=fields.split(',');fields.forEach(function(field){t396_elem__renderViewOneField(element,field)})}
function t396_elem__renderViewOneField(element,field){element=t396_getEl(element);if(!element)return;var value=t396_elem__getFieldValue(element,field);var elementType;var borderWidth;var borderStyle;var currentValue;var slidesMain;var slidesImg;switch(field){case 'left':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.left=parseFloat(value).toFixed(1)+'px';break;case 'top':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.top=parseFloat(value).toFixed(1)+'px';break;case 'width':value=t396_elem__getWidth(element,value);element.style.width=parseFloat(value).toFixed(1)+'px';elementType=element.getAttribute('data-elem-type');switch(elementType){case 'tooltip':var pinSvgIcon=element.querySelectorAll('.tn-atom__pin-icon');Array.prototype.forEach.call(pinSvgIcon,function(pin){var pinSize=parseFloat(value).toFixed(1)+'px';pin.style.width=pinSize;pin.style.height=pinSize});element.style.height=parseInt(value).toFixed(1)+'px';break;case 'gallery':borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.width=currentValue;if(slidesMain)slidesMain.style.width=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.width=currentValue});break}
break;case 'height':elementType=element.getAttribute('data-elem-type');if(elementType==='tooltip')return;value=t396_elem__getHeight(element,value);element.style.height=parseFloat(value).toFixed(1)+'px';if(elementType==='gallery'){borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.height=currentValue;if(slidesMain)slidesMain.style.height=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.height=currentValue})}
break;case 'container':t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top');break;case 'inputs':var textArea=element.querySelector('.tn-atom__inputs-textarea');value=textArea?textArea.value:'';try{t_zeroForms__renderForm($(element),value)}catch(err){}
break}
if(field==='width'||field==='height'||field==='fontsize'||field==='fontfamily'||field==='letterspacing'||field==='fontweight'||field==='img'){t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top')}}
function t396_elem__convertPosition__Local__toAbsolute(element,field,value){element=t396_getEl(element);if(!element)return;var artBoard=element.closest('.t396__artboard');var verticalAlignValue=t396_ab__getFieldValue(artBoard,'valign');var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isTildaModeEdit=tildaMode==='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var valueAxisY=t396_elem__getFieldValue(element,'axisy');var valueAxisX=t396_elem__getFieldValue(element,'axisx');var container=t396_elem__getFieldValue(element,'container');value=parseInt(value);var elementContainer;var offsetLeft;var offsetTop;var elementWidth;var elementContainerWidth;var elementHeight;var elementContainerHeight;switch(field){case 'left':elementContainer=container==='grid'?'grid':'window';offsetLeft=container==='grid'?window.tn.grid_offset_left:0;elementContainerWidth=container==='grid'?window.tn.grid_width:window.tn.window_width;var elementLeftUnits=t396_elem__getFieldValue(element,'leftunits');if(elementLeftUnits==='%'){value=t396_roundFloat(elementContainerWidth*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offsetLeft+value}
if(valueAxisX==='center'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth/2-elementWidth/2+value}
if(valueAxisX==='right'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth-elementWidth+value}
if(isScaledElement&&elementContainer!=='window'){elementWidth=t396_elem__getWidth(element);value=value+(elementWidth*window.tn_scale_factor-elementWidth)/2}
break;case 'top':var artBoardParent=element.parentNode;var proxyMinOffsetTop=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-offset-top'):'0';var proxyMinHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-max-height'):'0';var getElementHeight=function(element){var height=t396_elem__getHeight(element);if(element&&element.getAttribute('data-elem-type')==='image'){var width=t396_elem__getWidth(element);var fileWidth=t396_elem__getFieldValue(element,'filewidth');var fileHeight=t396_elem__getFieldValue(element,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);height=width/ratio}}
return height};elementContainer=container==='grid'?'grid':'window';offsetTop=container==='grid'?parseFloat(proxyMinOffsetTop):0;elementContainerHeight=container==='grid'?parseFloat(proxyMinHeight):parseFloat(proxyMaxHeight);var elTopUnits=t396_elem__getFieldValue(element,'topunits');if(elTopUnits==='%'){value=(elementContainerHeight*(value/100))}
if(isScaledElement&&elementContainer!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&elementContainer!=='window'){offsetTop=verticalAlignValue==='stretch'?0:(offsetTop/window.tn_scale_factor)}
value=offsetTop+value;var artBoardHeightVH=t396_ab__getFieldValue(artBoardParent,'height_vh');var artBoardMinHeight=t396_ab__getFieldValue(artBoardParent,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoardParent);if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
if(valueAxisY==='center'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight/2-elementHeight/2+value}
if(valueAxisY==='bottom'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight-elementHeight+value}
if(isScaledElement&&elementContainer!=='window'){elementHeight=getElementHeight(element);value=value+(elementHeight*window.tn_scale_factor-elementHeight)/2}
break}
return value}
function t396_ab__setFieldValue(artBoard,prop,val,resolution){if(!resolution)resolution=window.tn.curResolution;if(resolution<1200){if(artBoard)artBoard.setAttribute('data-artboard-'+prop+'-res-'+resolution,val)}else{if(artBoard)artBoard.setAttribute('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(artBoard,prop){if(!artBoard)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop)}
if(i>0&&+resolution===breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+breakpoint);if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+slicedBreakpoints[n]);if(dataField)break}}
if(!dataField)dataField=artBoard.getAttribute('data-artboard-'+prop)}});return dataField?dataField:''}
function t396_ab__renderViewOneField(artBoard,field){t396_ab__getFieldValue(artBoard,field)}
function t396_allelems__renderView(artBoard){if(!artBoard)return!1;tn_console('func: allelems__renderView: abid:'+artBoard.getAttribute('data-artboard-recid'));var ArtBoardelements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(ArtBoardelements,function(element){t396_elem__renderView(element)})}
function t396_ab__filterUpdate(artBoard){var filter=artBoard.querySelector('.t396__filter');if(!filter)return;var filterColorRgb=filter.getAttribute('data-filtercolor-rgb');var filterColorRgb2=filter.getAttribute('data-filtercolor2-rgb');var filterOpacity=filter.getAttribute('data-filteropacity');var filterOpacity2=filter.getAttribute('data-filteropacity2');if(filterColorRgb&&!filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb+','+filterOpacity+')'}else if(!filterColorRgb&&filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb2+','+filterOpacity2+')'}else if(filterColorRgb&&filterColorRgb2){filter.style.background='-webkit-gradient(linear, left top, left bottom, from(rgba('+filterColorRgb+','+filterOpacity+')), to(rgba('+filterColorRgb2+','+filterOpacity2+')) )'}else{filter.style.backgroundColor='transparent'}}
function t396_ab__getHeight(artBoard,artBoardHeight){if(!artBoardHeight)artBoardHeight=t396_ab__getFieldValue(artBoard,'height');artBoardHeight=parseFloat(artBoardHeight);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(artBoardHeightVH){artBoardHeightVH=parseFloat(artBoardHeightVH);if(!isNaN(artBoardHeightVH)){var artBoardHeightVHpx=window.tn.window_height*artBoardHeightVH/100;if(artBoardHeight<artBoardHeightVHpx){artBoardHeight=artBoardHeightVHpx}}}
return artBoardHeight}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'width');value=parseFloat(value);var elWidthUnits=t396_elem__getFieldValue(element,'widthunits');if(elWidthUnits==='%'){var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=window.tn.window_width*value/100}else{value=window.tn.grid_width*value/100}}
return value}
function t396_elem__getHeight(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'height');value=parseFloat(value);var elemType=element.getAttribute('data-elem-type');if(elemType==='shape'||elemType==='video'||elemType==='html'||elemType==='gallery'){var elHeightUnits=t396_elem__getFieldValue(element,'heightunits');if(elHeightUnits==='%'){var artBoard=element.parentNode;var proxyMinHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-max-height'):'0';var artBoardMinHeight=parseFloat(proxyMinHeight);var artBoardMaxHeight=parseFloat(proxyMaxHeight);var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=artBoardMaxHeight*(value/100)}else{value=artBoardMinHeight*(value/100)}}}else if(elemType!=='button'){value=element.clientHeight}
return value}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(+(window.tn_comments)===1)console.log(str)}
function t396_setUpTooltip_desktop(element,tooltip,tooltipContent){element=t396_getEl(element);var timer;if(tooltip){tooltip.addEventListener('mouseover',function(){var visibleEls=document.querySelectorAll('.tn-atom__tip_visible');Array.prototype.forEach.call(visibleEls,function(visibleEl){var curTipEl=visibleEl.closest('.t396__elem');var cirTipElID=curTipEl?curTipEl.getAttribute('data-elem-id'):'';if(cirTipElID!==element.getAttribute('data-elem-id')){t396_hideTooltip(curTipEl,visibleEl)}});clearTimeout(timer);if(tooltipContent&&tooltipContent.style.display==='block')return;t396_showTooltip(element,tooltipContent)});tooltip.addEventListener('mouseout',function(){timer=setTimeout(function(){t396_hideTooltip(element,tooltipContent)},300)})}}
function t396_setUpTooltip_mobile(element,tooltip,tooltipContent){element=t396_getEl(element);if(tooltip){tooltip.addEventListener('click',function(){if(tooltipContent&&tooltipContent.style.display==='block'&&tooltip.classList.contains('tn-atom__pin')){t396_hideTooltip(element,tooltipContent)}else{t396_showTooltip(element,tooltipContent)}})}
var elementID=element.getAttribute('data-elem-id');document.addEventListener('click',function(e){if(e.target.closest('.tn-atom__pin')){var zbEl=e.target.closest('.t396__elem');var clickedPinId=zbEl?zbEl.getAttribute('data-elem-id'):'';if(clickedPinId===elementID)return}
t396_hideTooltip(element,tooltipContent)})}
function t396_hideTooltip(element,tooltipContent){if(tooltipContent)tooltipContent.style.display='';if(tooltipContent)tooltipContent.style.left='';if(tooltipContent)tooltipContent.style.transform='';if(tooltipContent)tooltipContent.style.right='';if(tooltipContent)tooltipContent.classList.remove('tn-atom__tip_visible');if(element)element.style.zIndex=''}
function t396_showTooltip(element,tooltipContent){element=t396_getEl(element);var pos=element.getAttribute('data-field-tipposition-value');if(!pos)pos='top';var elSize=element.clientHeight;var elTop=element.getBoundingClientRect().top+window.pageYOffset;var elBottom=elTop+elSize;var elLeft=element.getBoundingClientRect().left+window.pageXOffset;var elRight=elLeft+elSize;var winTop=window.pageYOffset;var winWidth=document.documentElement.clientWidth;var winBottom=winTop+document.documentElement.clientHeight;var tipElHeight=tooltipContent?tooltipContent.offsetHeight:0;var tipElWidth=tooltipContent?tooltipContent.offsetWidth:0;var padding=15;var tipElRight;var tipElLeft;var tipElTop;var tipElBottom;if(pos==='right'||pos==='left'){tipElRight=elRight+padding+tipElWidth;tipElLeft=elLeft-padding-tipElWidth;if((pos==='right'&&tipElRight>winWidth)||(pos==='left'&&tipElLeft<0)){pos='top'}}
if(pos==='top'||pos==='bottom'){tipElRight=elRight+(tipElWidth/2-elSize/2);tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padding);if(tooltipContent)tooltipContent.style.left='auto';if(tooltipContent)tooltipContent.style.transform='none';if(tooltipContent)tooltipContent.style.right=rightOffset+'px'}
if(tipElLeft<0){var leftOffset=-(elLeft-padding);if(tooltipContent)tooltipContent.style.left=leftOffset+'px';if(tooltipContent)tooltipContent.style.transform='none'}}
if(pos==='top'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos==='bottom'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
if(tooltipContent)tooltipContent.setAttribute('data-tip-pos',pos);if(tooltipContent)tooltipContent.style.display='block';if(tooltipContent)tooltipContent.classList.add('tn-atom__tip_visible');if(element)element.style.zIndex='1000'}
function t396_hex2rgba(hexStr,opacity){if(!hexStr)return!1;var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t396_removeElementFromDOM(el){el=t396_getEl(el);if(el&&el.parentNode){el.parentNode.removeChild(el)}}
function t396_getEl(el){if(el instanceof jQuery){return el.length?el.get(0):null}else{return el}}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t446_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var linkItems=rec.querySelectorAll('.t-menu__link-item');var subMenuLinks=rec.querySelectorAll('.t-menusub__link-item');Array.prototype.forEach.call(linkItems,function(link){link.addEventListener('click',function(){if(link.classList.contains('t-menusub__target-link')||link.classList.contains('tooltipstered')||link.classList.contains('t794__tm-link')||link.classList.contains('t966__tm-link')||link.classList.contains('t978__tm-link'))return;t446_hideMenuOnMobile(link,rec)})});Array.prototype.forEach.call(subMenuLinks,function(subMenuLink){subMenuLink.addEventListener('click',function(){t446_hideMenuOnMobile(subMenuLink,rec)})})}
function t446_setLogoPadding(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t446');var logo=menu?menu.querySelector('.t446__logowrapper'):null;var logoWidth=logo?logo.offsetWidth:0;var leftWrapper=menu?menu.querySelector('.t446__leftwrapper'):null;var rightWrapper=menu?menu.querySelector('.t446__rightwrapper'):null;if(leftWrapper)leftWrapper.style.paddingRight=((logoWidth/2)+50)+'px';if(rightWrapper)rightWrapper.style.paddingLeft=((logoWidth/2)+50)+'px'}
function t446_checkOverflow(recid,menuheight){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t446'):null;if(!menu)return;var rightWrapper=menu.querySelector('.t446__rightwrapper');var rightMenuWrap=rightWrapper?rightWrapper.querySelector('.t446__rightmenuwrapper'):null;var additionalWrap=rightWrapper?rightWrapper.querySelector('.t446__additionalwrapper'):null;var burgerWrapOverflow=rightWrapper?rightWrapper.querySelector('.t446__burgerwrapper_overflow'):null;var burgerWrap=rightWrapper?rightWrapper.querySelector('.t446__burgerwrapper_withoutoverflow'):null;var rightWrapperWidth=rightWrapper?rightWrapper.offsetWidth:0;var rightMenuWrapWidth=rightMenuWrap?rightMenuWrap.offsetWidth:0;var additionalWrapWidth=additionalWrap?additionalWrap.offsetWidth:0;var additionalWrapFloating=additionalWrap?additionalWrap.style.float||window.getComputedStyle(additionalWrap).float:'';var blockHeight=menuheight>0?menuheight:80;if(window.innerWidth>980&&rightMenuWrapWidth+additionalWrapWidth>rightWrapperWidth){menu.style.height=(blockHeight*2)+'px';if(additionalWrap)additionalWrap.style.float='right';if(burgerWrapOverflow)burgerWrapOverflow.style.display='table-cell';if(burgerWrap)burgerWrap.style.display='none'}else{if(menu.offsetHeight>blockHeight)menu.style.height=blockHeight+'px';if(additionalWrap&&additionalWrapFloating==='right')additionalWrap.style.float='none';if(burgerWrapOverflow)burgerWrapOverflow.style.display='none';if(burgerWrap)burgerWrap.style.display='table-cell'}}
function t446_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t446__list_item a[href=\''+url+'\'], '+'.t446__list_item a[href=\''+url+'/\'], '+'.t446__list_item a[href=\''+pathname+'\'], '+'.t446__list_item a[href=\'/'+pathname+'\'], '+'.t446__list_item a[href=\''+pathname+'/\'], '+'.t446__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t446_checkAnchorLinks(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<980)return;var navLinks=rec.querySelectorAll('.t446__list_item a[href*=\'#\']');navLinks=Array.prototype.filter.call(navLinks,function(link){return!link.classList.contains('tooltipstered')});if(navLinks.length)t446_catchScroll(navLinks)}
function t446_catchScroll(navLinks){var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t446_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t446_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t446_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t446').bind('displayChanged',function(){t446_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t446_updateSectionsOffsets(sections)})})}
setInterval(function(){t446_updateSectionsOffsets(sections)},5000);t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t446_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t446_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t446_getSectionByHref(currentLink){if(!currentLink)return;var currentLinkValue=currentLink.href?currentLink.href.replace(/\s+/g,''):'';if(currentLinkValue.indexOf('/')===0)currentLinkValue=currentLinkValue.slice(1);if(currentLink.href&&currentLink.matches('[href*="#rec"]')){currentLinkValue=currentLinkValue.replace(/.*#/,'');return document.getElementById(currentLinkValue)}else{var recordElements=document.querySelectorAll('.r[data-record-type=\'215\']');recordElements=Array.prototype.filter.call(recordElements,function(element){return element.querySelector('a[name=\''+currentLinkValue.slice(1)+'\']')});return recordElements.length?recordElements[0]:null}}
function t446_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t446_setBg(recid){var menuBlocks=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t446_appearMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset&&appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t446_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t446_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}})}
function t446_slideUpElement(menu,menuHeight,direction){var diff=direction==='toTop'?0:menuHeight;var diffOpacity=direction==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=direction==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=direction==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(direction==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(direction==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t446_changebgopacitymenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t446');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t446_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t446');var burger=rec.querySelector('.t446__mobile');if(menu&&menu.classList.contains('t446__mobile_burgerhook')){var mobileBurger=burger?burger.querySelector('.t446__mobile_burger'):null;if(mobileBurger){var mobileBurgerParent=mobileBurger.parentElement;var link=document.createElement('a');link.href='#menuopen';if(mobileBurgerParent){link.appendChild(mobileBurger);mobileBurgerParent.appendChild(link)}}}else if(burger){burger.addEventListener('click',function(){console.log('click');if(burger.classList.contains('t446_opened')){t446_fadeOut(menu,300);burger.classList.remove('t446_opened')}else{t446_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t446_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu)menu.style.opacity='';if(menu)menu.style.display='';if(burger)burger.classList.remove('t446_opened')}},200));var linkItems=rec.querySelectorAll('.t-menu__link-item');Array.prototype.forEach.call(linkItems,function(link){link.addEventListener('click',function(){if(!link.classList.contains('t966__tm-link')&&!link.classList.contains('t978__tm-link')){t446_hideMenuOnMobile(link,rec)}})});var logoWrappers=rec.querySelectorAll('.t446__logowrapper2 a');Array.prototype.forEach.call(logoWrappers,function(logoWrapper){logoWrapper.addEventListener('click',function(){t446_hideMenuOnMobile(link,rec)})})}
function t446_hideMenuOnMobile(link,rec){if(!rec||!link||window.innerWidth>=980)return!1;var url=link.href?link.href.trim():'';var menu=rec.querySelector('.t446');var burger=rec.querySelector('.t446__mobile');if(url&&link.matches('[href*="#"]')){if(burger)burger.classList.remove('t446_opened');if(menu)t446_fadeOut(menu,300)}}
function t446_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t446_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t480_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;t480_setHeight(recId);if(window.isMobile){if(typeof jQuery!=='undefined'){$(window).on('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}else{window.addEventListener('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}}else{window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t480_setHeight(recId)}))}
if(typeof jQuery!=='undefined'){$(container).on('displayChanged',function(){t480_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t480_setHeight(recId)})}}
function t480_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var sizer=rec.querySelector('.t480__sizer');var sizerStyle=getComputedStyle(sizer,null);var sizerPaddingTop=parseInt(sizerStyle.paddingTop);var sizerPaddingBottom=parseInt(sizerStyle.paddingBottom);var sizerPaddingLeft=parseInt(sizerStyle.paddingLeft);var sizerPaddingRight=parseInt(sizerStyle.paddingRight);var sizerHeight=sizer.clientHeight-(sizerPaddingTop+sizerPaddingBottom);var sizerWidth=sizer.clientWidth-(sizerPaddingLeft+sizerPaddingRight);var ratio=sizerWidth/sizerHeight;var imgWrapper=rec.querySelector('.t480__blockimg');var imgWidth=imgWrapper.clientWidth;var sizerAttrStyle=sizer.getAttribute('style');var windowHeight=window.innerHeight;if(window.isMobile&&sizerAttrStyle&&sizerAttrStyle.indexOf('vh')!==-1){sizerHeight=document.documentElement.clientHeight*parseFloat(windowHeight/sizerHeight);imgWrapper.style.height=(imgWidth/ratio)+'px'}else if(sizerHeight!=windowHeight){imgWrapper.style.height=(imgWidth/ratio)+'px'}}
function t505__createPieChart(recId,data1,data2,data3,data4,sectorColor,pieBgColor,bgcolor,blocksNumber,diagramWidth,diameter){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t505');if(!container)return;var radius;if(diameter>300||diameter==''||diameter<100){if(diameter==''){radius=100;diameter=200}
if(diameter>300){radius=150;diameter=300}
if(diameter<100){radius=50;diameter=100}}else{radius=diameter/2}
if(diagramWidth=='')diagramWidth=10;if(diagramWidth>radius)diagramWidth=10;if(diagramWidth<1)diagramWidth=1;if(window.devicePixelRatio>=2){var oldSize=diameter;radius=radius*2;diameter=diameter*2;diagramWidth=diagramWidth*2}
var correction=+diagramWidth/2;var dataArray=[data1,data2,data3,data4];for(var i=0;i<4;i++){if(dataArray[i]!=''&&blocksNumber>i){var canvas=rec.querySelector('.t505__pie'+(i+1));canvas.setAttribute('width',diameter);canvas.setAttribute('height',diameter);var context=canvas.getContext('2d');if(window.devicePixelRatio>=2){canvas.style.width=oldSize+'px';canvas.style.height=oldSize+'px'}
for(var j=0;j<2;j++){if(j===1&&dataArray[i]==0)continue;if(j==0){context.strokeStyle=pieBgColor;var angle=Math.PI*2;context.lineWidth=diagramWidth-1}else{context.strokeStyle=sectorColor;var angle=Math.PI*2*(dataArray[i]/100);context.lineWidth=diagramWidth}
context.beginPath();context.lineCap='round';context.moveTo(diameter-correction,radius);context.arc(radius,radius,radius-correction,0,angle,!1);context.stroke()}}}}
function t531_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t531');if(!container)return;var images=rec.querySelectorAll('.t531__blockimg');if(!images[0])return;var imageWidth=images[0].getAttribute('data-image-width');var imageHeight=images[0].getAttribute('data-image-height');var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;for(var i=0;i<images.length;i++){images[i].style.paddingBottom=imagePadding+'%'}
if(window.innerWidth>480){var textWrappers=rec.querySelectorAll('.t531__textwrapper');var imageWrapperHeight=rec.querySelector('.t531__imgwrapper').clientHeight;for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height=imageWrapperHeight+'px'}}}
function t604_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;t604_imageHeight(recid);t604_arrowWidth(recid);t604_show(recid);t604_hide(recid);window.addEventListener('resize',t_throttle(function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)}));if(typeof jQuery!=='undefined'){$(rec).find('.t604').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}else{var currentBlock=rec.querySelector('.t604');if(currentBlock){currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}}}
function t604_show(recid){var rec=document.getElementById('rec'+recid);var playBtns=rec.querySelectorAll('.t604__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var parent=play.parentElement;var videoBg=parent?parent.querySelector('.t-slds__bgimg'):null;if(videoBg)videoBg.style.opacity='0';var sliderVideo=play.getAttribute('data-slider-video-type');var url=play.getAttribute('data-slider-video-url');var nextEl=play.nextElementSibling;if(nextEl)nextEl.style.zIndex='3';var iframe;switch(sliderVideo){case 'youtube':iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break;case 'vimeo':var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'?autoplay=1&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break}})})}
function t604_hide(recid){var rec=document.getElementById('rec'+recid);var frames=rec.querySelectorAll('.t604__frame');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(frames,function(frame){frame.innerHTML='';frame.style.zIndex=''})})}
function t604_imageHeight(recid){var rec=document.getElementById('rec'+recid);var images=rec.querySelectorAll('.t604__separator');Array.prototype.forEach.call(images,function(image){var imgHeight=image.getAttribute('data-slider-image-height');var imgWidth=image.getAttribute('data-slider-image-width');var imgRatio=imgHeight/imgWidth;var imgPadding=imgRatio*100;image.style.paddingBottom=imgPadding+'%'})}
function t604_arrowWidth(recid){var rec=document.getElementById('rec'+recid);var arrows=rec.querySelectorAll('.t-slds__arrow_wrapper');var slide=rec.querySelector('.t-slds__wrapper');var slideWidth=slide?slide.offsetWidth:0;var arrowWidth=window.innerWidth-slideWidth;Array.prototype.forEach.call(arrows,function(arrow){arrow.style.width=window.innerWidth>960?(arrowWidth/2)+'px':''})}
function t668_init(recid){var el=$('#rec'+recid);var toggler=el.find(".t668__header");var accordion=el.find('.t668__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t668__opened").next().slideUp()}
$(this).toggleClass("t668__opened");$(this).next().slideToggle();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t678_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t678__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t678__fadeOut(tildaLabel,50)}},300)}else{t678__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t678__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t678__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t678__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t678__easeInOutCubic(currentTime,change){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t678__animateScroll(){currentTime+=increment;window.scrollTo(0,t678__easeInOutCubic(currentTime,change));if(currentTime<duration){setTimeout(t678__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t678__animateScroll()}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t702_resizePopup(recId);t702__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup()});popupCloseBtn.addEventListener('click',t702_closePopup);if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var range=rec.querySelector('.t-range');var documentBody=document.body;popup.style.display='block';if(range)t702__triggerEvent(range,'popupOpened');setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
document.addEventListener('keydown',t702_escClosePopup);t702__lazyLoad()}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup()}
function t702_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t702__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t702_escClosePopup)}
function t702_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t702__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t702__fadeOut(tildaLabel)}},300)}else{t702__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t702__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t702__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t702__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t702__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t702__animateScroll(){currentTime+=increment;window.scrollTo(0,t702__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t702__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t702__animateScroll()}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}
if(t702__checkJqueryEvent(el,eventName)){$(el).trigger(eventName)}}
function t702__checkJqueryEvent(element,eventName){var events=$._data(element,'events')||!1;var isEvent=!1;if(events){for(var key in events){if(key===eventName){isEvent=!0;break}}}
return isEvent}
function t764_init(recid){var rec=document.getElementById('rec'+recid);t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderContainer=rec.querySelector('.t-slds__container');var sliderWidth=sliderContainer?sliderContainer.offsetWidth:0;var sliderPos=sliderWrapper?sliderWrapper.getAttribute('data-slider-pos'):'0';var pos=parseFloat(sliderPos);if(sliderWrapper)sliderWrapper.style.transform='translate3d(-'+(sliderWidth*pos)+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)});var currentBlock=rec.querySelector('.t764');if(currentBlock){currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}}
function t817_init(recid){var rec=$('#rec'+recid);var curMode=$('.t-records').attr('data-tilda-mode');var tab=rec.find('.t817__tab');var select=rec.find('.t817__select');var content=rec.find('.t817__content');if(curMode!='edit'&&curMode!='preview'){t817_scrollToTabs(recid)}
t817_showTabByUrl(recid,tab,content,select);t817_showTab(tab,content,recid);t817_showTabMobile(select,content,recid)}
function t817_showTab(tab,content,recid){var tabNumber;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');tab.on('click',function(e){tabNumber=$(this).attr('data-tab-number');tab.removeClass('t817__tab_active');content.removeClass('t817__content_active');$(this).addClass('t817__tab_active');t817_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumber){$(content[i]).addClass('t817__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t817_showTabMobile(select,content,recid){var tabNumberMobile;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');select.change(function(e){tabNumberMobile=$(this).val();content.removeClass('t817__content_active');t817_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumberMobile){$(content[i]).addClass('t817__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t817_showTabByUrl(recid,tab,content,select){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf(recid+'-');var tabIndex=curUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!=-1){tab.each(function(i){if($(tab[i]).attr('data-tab-number')==tabIndex){$(tab[i]).addClass('t817__tab_active')}});content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabIndex){$(content[i]).addClass('t817__content_active')}});select.val(tabIndex)}else{tab.first().addClass('t817__tab_active');content.first().addClass('t817__content_active')}}
function t817_scrollToTabs(recid){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');var tabIndexNumberStart=curUrl.indexOf('tab/');if(tabIndexNumber!=-1){var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length)
if(+tabRec==+recid){var tabBlock=$('#rec'+tabRec).find('.t817');var targetOffset=tabBlock.offset().top;if($(window).width()>960){var target=targetOffset-200}else{var target=targetOffset-100}
$('html, body').animate({scrollTop:target},300)}}}
function t817_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!=-1){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}}}
function t819_init(recid){var rec=$('#rec'+recid);var curMode=$('.t-records').attr('data-tilda-mode');var tab=rec.find('.t819__tab');var select=rec.find('.t819__select');var content=rec.find('.t819__content');if(curMode!='edit'&&curMode!='preview'){t819_scrollToTabs(recid)}
t819_showTabByUrl(recid,tab,content,select);t819_showTab(tab,content,recid);t819_showTabMobile(select,content,recid)}
function t819_showTab(tab,content,recid){var tabNumber;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');tab.on('click',function(e){tabNumber=$(this).attr('data-tab-number');tab.removeClass('t819__tab_active');content.removeClass('t819__content_active');$(this).addClass('t819__tab_active');t819_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumber){$(content[i]).addClass('t819__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t819_showTabMobile(select,content,recid){var tabNumberMobile;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');select.change(function(e){tabNumberMobile=$(this).val();content.removeClass('t819__content_active');t819_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumberMobile){$(content[i]).addClass('t819__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
e.preventDefault()})}
function t819_showTabByUrl(recid,tab,content,select){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf(recid+'-');var tabIndex=curUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!=-1){tab.each(function(i){if($(tab[i]).attr('data-tab-number')==tabIndex){$(tab[i]).addClass('t819__tab_active')}});content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabIndex){$(content[i]).addClass('t819__content_active')}});select.val(tabIndex)}else{tab.first().addClass('t819__tab_active');content.first().addClass('t819__content_active')}}
function t819_scrollToTabs(recid){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');var tabIndexNumberStart=curUrl.indexOf('tab/');if(tabIndexNumber!=-1){var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length)
if(+tabRec==+recid){var tabBlock=$('#rec'+tabRec).find('.t819');var targetOffset=tabBlock.offset().top;if($(window).width()>960){var target=targetOffset-200}else{var target=targetOffset-100}
$('html, body').animate({scrollTop:target},400)}}}
function t819_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!=-1){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}}}
function t851_init(recId){t851_updateLazyLoad(recId)}
function t851_updateLazyLoad(recId){var scrollContainer=document.querySelector('#rec'+recId+' .t851__container_mobile-flex');var allRecords=document.getElementById('allrecords');var currentMode=allRecords.getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}}
function t868_setHeight(recid){var rec=$('#rec'+recid);var div=rec.find('.t868__video-carier');var height=div.width()*0.5625;div.height(height);div.parent().height(height)}
function t868_initPopup(recid){var rec=$('#rec'+recid);$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup');var hook=el.attr('data-tooltip-hook');var analitics=el.attr('data-track-popup');var customCodeHTML=t868__readCustomCode(rec);if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t868_showPopup(recid,customCodeHTML);t868_resizePopup(recid);e.preventDefault();if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t868__readCustomCode(rec){var customCode=rec.find('.t868 .t868__code-wrap').html();rec.find('.t868 .t868__code-wrap').remove();return customCode}
function t868_showPopup(recid,customCodeHTML){var rec=$('#rec'+recid);var popup=rec.find('.t-popup');var popupContainer=rec.find('.t-popup__container');popupContainer.html(customCodeHTML);popup.css('display','block');t868_setHeight(recid);setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');rec.find('.t-popup').click(function(e){var container;if(e.target){container=e.target.closest('.t-popup__container')}
if(!container){t868_closePopup(recid)}});rec.find('.t-popup__close').click(function(e){t868_closePopup(recid)});rec.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(url.indexOf('#order')!=-1){var popupContainer=rec.find('.t-popup__container');setTimeout(function(){popupContainer.empty()},600)}
if(!url||url.substring(0,7)!='#price:'){t868_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t868_closePopup(recid)}})}
function t868_closePopup(recid){var rec=$('#rec'+recid);var popup=rec.find('.t-popup');var popupContainer=rec.find('.t-popup__container');$('body').removeClass('t-body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');popupContainer.empty();setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t868_resizePopup(recid){var rec=$('#rec'+recid);var div=rec.find('.t-popup__container').height();var win=$(window).height();var popup=rec.find('.t-popup__container');if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t868_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}